// packages/sdk-react/src/components/ui/FusionAuthAccountButton/index.tsx
import { FC } from 'react';
import classNames from 'classnames';

import { useFusionAuth } from '#components/providers/FusionAuthProvider';
import styles from '#styles/button.module.scss';

interface Props {
  className?: string;
}

export const FusionAuthAccountButton: FC<Props> = ({ className }) => {
  const { manageAccount } = useFusionAuth();

  return (
    <button
      className={classNames(styles.fusionAuthButton, className)}
      type="button"
      onClick={manageAccount}
    >
      Manage Account
    </button>
  );
};

// packages/sdk-vue/src/components/FusionAuthAccountButton/FusionAuthAccountButton.vue
<script setup lang="ts">
import { useFusionAuth } from '#/composables/useFusionAuth.ts';
const { manageAccount } = useFusionAuth();
</script>

<template>
  <button class="fusionauth-button" @click="manageAccount()">
    <slot>Manage Account</slot>
  </button>
</template>

<style lang="scss" scoped>
@import '#/styles/button.scss';
</style>
