// packages/sdk-react/src/components/ui/FusionAuthRegisterButton.tsx
import { FC } from 'react';
import { useFusionAuth } from '../providers/FusionAuthProvider';
import styles from '../../styles/button.module.scss';
import classNames from 'classnames';

interface Props {
    state?: string;
    text?: string;
    className?: string;
}

export const FusionAuthRegisterButton: FC<Props> = ({
    state,
    text,
    className,
}) => {
    const { register } = useFusionAuth();

    return (
        <button
            className={classNames(styles.fusionAuthButton, className)}
            type="button"
            onClick={() => register(state ?? '')}
        >
            {text ?? 'Register Now'}
        </button>
    );
};

// packages/sdk-vue/src/components/FusionAuthRegisterButton.vue
<template>
  <button class="register-button" @click="doRegister()">
    <slot>Register</slot>
  </button>
</template>

<script setup lang="ts">
import { useFusionAuth } from '../composables/useFusionAuth.ts';

const fusionAuth = useFusionAuth();

const props = defineProps<{
  state?: string;
}>();

function doRegister() {
  fusionAuth.register(props.state);
}
</script>

<style lang="scss" scoped>
@import '../styles/button.scss';

.register-button {
  @extend .fusionauth-button;
}
</style>
