// packages/sdk-vue/src/components/FusionAuthLoginButton/FusionAuthLoginButton.vue
<template>
  <button class="login-button" @click="doLogin()">
    <slot>Login</slot>
  </button>
</template>

<script setup lang="ts">
import { useFusionAuth } from '#/composables/useFusionAuth';

const fusionAuth = useFusionAuth();

const props = defineProps<{
  state?: string;
}>();

function doLogin() {
  fusionAuth.login(props.state);
}
</script>

<style lang="scss" scoped>
@import '#/styles/button.scss';

.login-button {
  @extend .fusionauth-button;
}
</style>

// packages/sdk-react/src/components/ui/FusionAuthLoginButton.tsx
import { FC } from 'react';
import { useFusionAuth } from '../providers/FusionAuthProvider';
import styles from '../../styles/button.module.scss';
import classNames from 'classnames';

interface Props {
    state?: string;
    text?: string;
    className?: string;
}

export const FusionAuthLoginButton: FC<Props> = ({
    state,
    text,
    className,
}) => {
    const { login } = useFusionAuth();

    return (
        <button
            className={classNames(styles.fusionAuthButton, className)}
            type="button"
            onClick={() => login(state ?? '')}
        >
            {text ?? 'Login'}
        </button>
    );
};
