// packages/sdk-react/src/components/ui/RequireAuth/index.tsx
import { FC, PropsWithChildren } from 'react';
import { useFusionAuth } from '#components/providers/FusionAuthProvider';

interface Props extends PropsWithChildren {
  withRole?: string | string[];
}

export const RequireAuth: FC<Props> = ({ withRole, children }) => {
  const { userInfo, isLoggedIn } = useFusionAuth();

  // Check if the user has the required role
  // withRole can be a string or an array of strings
  const hasRole = withRole
    ? ([] as string[])
        .concat(withRole)
        .some(role => userInfo?.roles?.includes(role))
    : true;

  const isAuthorized = isLoggedIn && hasRole;

  return <>{isAuthorized && children}</>;
};

// packages/sdk-vue/src/components/RequireAuth/RequireAuth.vue
<template>
  <template v-if="isAuthorized">
    <slot></slot>
  </template>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { useFusionAuth } from '#/composables/useFusionAuth';

const props = defineProps<{
  withRole?: string | string[];
}>();

const { isLoggedIn, userInfo } = useFusionAuth();

const isAuthorized = computed(() => {
  if (!isLoggedIn.value === true || userInfo.value === null) {
    return false;
  }

  if (!props.withRole) {
    return true;
  }

  const roles = Array.isArray(props.withRole)
    ? props.withRole
    : [props.withRole];
  const userRoles = userInfo.value?.roles ?? [];

  const isAuthenticated = isLoggedIn.value === true;
  const isAuthorized = userRoles.some(role => roles.includes(role));

  return isAuthenticated && isAuthorized;
});
</script>
