// packages/sdk-vue/src/components/FusionAuthAccountButton/FusionAuthAccountButton.vue
<script setup lang="ts">
import { useFusionAuth } from '#/composables/useFusionAuth.ts';
const { manageAccount } = useFusionAuth();
</script>

<template>
  <button class="fusionauth-button" @click="manageAccount()">
    <slot>Manage Account</slot>
  </button>
</template>

<style lang="scss" scoped>
@import '#/styles/button.scss';
</style>

// packages/sdk-angular/projects/fusionauth-angular-sdk/src/lib/components/fusionauth-account.button/fusion-auth-account-button.component.ts
import { Component } from '@angular/core';
import { FusionAuthService } from '../../fusion-auth.service';

@Component({
  selector: 'fa-account',
  templateUrl: './fusion-auth-account-button.component.html',
  styleUrls: ['./fusion-auth-account-button.component.scss'],
})
export class FusionAuthAccountButtonComponent {
  constructor(private fusionAuth: FusionAuthService) {}

  manageAccount() {
    this.fusionAuth.manageAccount();
  }
}

<button class="fa-button" (click)="manageAccount()">
  <span>manage account</span>
</button>
